### ISSUE TITLE
Issues with solaris / 64bit elf

### ISSUE THREAD

**Issue by brianhorakh** [jackeylu/mysql2redis#1]
Makefile for Solaris should probably have:
install:
-m64 parameter
otherwise gets ELFCLASS32 on default mysql for solaris (which is 64 bit)

I managed to re-compile libhiredis (64bit) by adding a -m64 then installed, now I'm stuck:

mysql> CREATE FUNCTION lib_mysqludf_redis_info RETURNS string SONAME 'lib_mysqludf_redis.so';

ERROR 1126 (HY000): Can't open shared library 'lib_mysqludf_redis.so' (errno: 0 ld.so.1: mysqld: fatal: libhiredis.so.0.10: open failed: No such file or directory)

**Comment by brianhorakh** [comment]
in the end for solaris 10 + mysql 5.5.29 - to compile under gcc required tweaking the make file so the compilation string looked like:

gcc -DMYSQL_DYNAMIC_PLUGIN -O2 -m64 -I/usr/local/mysql/include/ -I/usr/local/include -I. -fPIC -shared lib_mysqludf_redis.c utils.c -static-libgcc -lhiredis -L/usr/local/mysql/lib/plugin -o /usr/local/mysql/lib/plugin/lib_mysqludf_redis.so

The command above is sub-optimal statically links gcc + hiredis (since the default mysql for solaris is compiled with the sun compiler - which I don't have [[but am currently downloading]])

then run the create function commands in the lib_mysqludf_redis.sql file, restart the mysql server and it works!

**Comment by jackeylu** [comment]
Thank you, brianhorakh. 

I believe that you are right, but I don't have the test environment of Solaris + 64bits, and I don't know how to merge your make script into the Makefile gracefully, so I won't merge it.

But if you can do it, then you can push your new script. 

Thanks again.

**Comment by aborn** [comment]
libhiredis.so.0.10 missing, you should install it first.
